# Generated by Django 5.2.2 on 2025-06-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=100)),
                ("services", models.JSONField()),
                ("logo", models.ImageField(upload_to="logos/")),
                ("drive_connected", models.BooleanField(default=False)),
                ("dropbox_connected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
